<template>
  <div id="doc" class="bg-[var(--primary-color)] bg-img">
    <div class="limit-width">
      <HeaderNav />
    </div>
    <PageHeader title="Projects" />
    <div class="limit-width">
      <div class="w-[96%] mx-auto">
        <h1
          class="md:pt-20 pt-10 pb-6 text-center font-semibold text-3xl text-slate-600"
        >
          Ongoing Projects
        </h1>
        <div class="projects-container">
          <ProjectsProject
            title="Self-correcting ML-driven Synthesis of Network Designs from Hints"
            content="Despite much progress, the goal of driving network design from higher level intent remains elusive. 
            The challenges stem from the fact that while network architects often do have informal knowledge of 
             conditions under which their network must operate, existing design tools (based on optimization and constraint 
            solvers) need \textbf{precise} characterizations of these conditions. The goal of this project is to automate the 
            process of designing networks from informal operator hints. The proposal will tackle this goal through recent 
            developments in ML, and ML-based techiques for network design." 
           />

          <ProjectsProject
            title="ML-Driven Online Traffic Analysis at Multi-Terabit Line Rates"
            content="Self-driving networks, i.e., networks driven by real-time analytics performed on data at line-rate guided by programmatic control, 
            can help to ensure better network security and aid with performance diagnosis and repair. Realizing such a network often require machine 
            learning (ML) inferencing algorithms (e.g., to detect anomalous traffic). Unfortunately, as network bandwidth grows to hundreds of gigabits 
            to even terabits per second, it is challenging to analyze network traffic at line rates today. Many production intrusion detection systems 
            rely on out-of-band analysis resulting in slow reaction times that may take the order of minutes to resolve security issues
            besides requiring significant bandwidth to export data from routers. This project is tackling the challenge of inline traffic analysis 
            using programmable switches and programmable hardware. 
           />
            
          <ProjectsProject
            title="Next Generation Multi-Perspective Video Delivery at Internet Scale"
            content="The success of streaming video has generated interest in newer forms of multi-perspective video content, such as those generated by 360-degree cameras, multi-angle camera arrays, or light-field cameras. The immersive experience provided by these cameras can enhance user satisfaction. This project explores architectural enhancements, algorithms, and techniques to deliver multi-perspective video at Internet-scale."
          />

          <ProjectsProject
            title="A Program Synthesis Approach to Designing Networks with Indeterminate Objectives"
            content="Computer networks are difficult to manage since there exists a wide gulf between the high-level goals that operators have for their networks and the low-level decisions that operators should make. This project develops a novel framework that we term comparative synthesis (inspired by program synthesis from the Programming Language community), where a user's design objective, and the synthesis of a network design that optimizes that objective are done in tandem."
          />

          <ProjectsProject
            title="ML and Data-Driven Optimization of Internet Video Delivery from the Network Edge"
            content="Video dominates the Internet today, accounting for over 80% of Internet traffic by some estimates. A key challenge is delivering high quality Internet video over variable Internet environments. In this project, we are investigating whether high Quality of Experience can be enabled for Internet video by leveraging ML-frameworks at the network edge. Our work extensively uses insights from real-world data sets of Internet video sessions."
          />

          <ProjectsProject
            title="Causal ML models for Data-Driven Networking"
            content="A central theme of data-driven networking is answering what-if questions -- what would be the impact of changing the design of a networked system, given data obtained from a real-world deployment of an existing system. In this project, we are investigating the use of causal reasoning approaches to answer “what-if questions” using data collected from prior deployments of systems."
          />
        </div>
        <h1
          class="md:pt-20 pt-10 pb-6 text-center font-semibold text-3xl text-slate-600"
        >
          Past Projects
        </h1>
        <div class="projects-container">
          <ProjectsProject
            title="Synthesizing network designs with certifiable performance properties"
            content="Network design is ad-hoc today, and validating the design normally comes as an afterthought. Unlike the chip and software industry, where design and verification tools form a multi-billion dollar industry, network design and verification is still at an early stage. We are exploring approaches to synthesizing network designs with formally certifiable performance properties under failures. The work may be viewed as an early step towards verifying quanititative network properties."
          />
        </div>

      </div>
    </div>
    <div class="pb-[150px]"></div>
  </div>
</template>

<script type="module">
let projects_divs = [];
export default {
  methods: {
    overlap(element) {
      let topOverlap =
        (window.screen.height - element.getBoundingClientRect().top) /
        window.screen.height;
      if (topOverlap > 0.1) {
        element.classList.toggle("show-up");
        return true;
      }
      return false;
    },

    handleScroll() {
      var filtered = [];
      for (var idx in projects_divs) {
        if (this.overlap(projects_divs[idx])) {
          filtered.push(idx);
        }
      }
      for (var idx in filtered) {
        delete projects_divs[filtered[idx]];
      }
      if (Object.keys(projects_divs).length == 0) {
        window.removeEventListener("scroll", this.handleScroll);
      }
    },
  },
  mounted() {
    window.scrollTo(0, 0);
    projects_divs = [];
    let projects_divs_nodelist = document.querySelectorAll(
      ".project-container-div"
    );
    projects_divs_nodelist.forEach((projects_div) => {
      projects_divs.push(projects_div);
      if (projects_div.classList.contains("show-up")) {
        projects_div.classList.toggle("show-up");
      }
    });

    window.addEventListener("scroll", this.handleScroll);
    // in case height is small.
    this.handleScroll();
  },
};
</script>

